kafka:
  bootstrapAddress: localhost:9092
  topicName: "kafkaEmailTopic"
  groupId: "groupId"

aws:
  ses:
    template:
      email: emailTemplate
    fromEmail:
  access:
    ses:
  secret:
    ses:
  region:
    ses:
